# Generated by Django 3.0.1 on 2019-12-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_name', models.CharField(max_length=200)),
                ('Foster_time', models.CharField(max_length=200)),
                ('uaser', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('District_Service', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('Target_boundary', models.CharField(max_length=200)),
                ('u_id', models.CharField(max_length=200)),
                ('simulator', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=200)),
                ('time1', models.CharField(max_length=200)),
                ('time2', models.CharField(max_length=200)),
                ('Pit_type', models.CharField(max_length=200)),
            ],
        ),
    ]
