# Generated by Django 3.0.1 on 2019-12-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='uaser',
            new_name='user',
        ),
    ]
